import React from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, Legend } from 'recharts';
import { Bot, Sparkles, AlertTriangle, FileCheck } from 'lucide-react';
import { ProcessingStats } from './types.ts';

interface AnalysisViewProps {
  stats: ProcessingStats;
  aiAnalysis: string;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ stats, aiAnalysis }) => {
  const data = [
    { name: 'Valid', value: stats.validNumbers, color: '#22c55e' }, // green-500
    { name: 'Rule 1: Internal Dupes', value: stats.intraSheetDuplicates, color: '#eab308' }, // yellow-500
    { name: 'Rule 2: History Limit', value: stats.historicalDuplicates, color: '#ef4444' }, // red-500
  ];

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-8">
      {/* Chart Section */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-100">
        <h3 className="text-lg font-semibold text-slate-800 mb-4 flex items-center">
          <FileCheck className="w-5 h-5 mr-2 text-blue-600" />
          Distribution of Data Quality
        </h3>
        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={data}
                cx="50%"
                cy="50%"
                innerRadius={60}
                outerRadius={80}
                paddingAngle={5}
                dataKey="value"
              >
                {data.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={entry.color} />
                ))}
              </Pie>
              <Tooltip 
                contentStyle={{ borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
              />
              <Legend verticalAlign="bottom" height={36} iconType="circle"/>
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* AI Insights Section */}
      <div className="bg-gradient-to-br from-indigo-50 to-purple-50 p-6 rounded-xl border border-indigo-100 relative overflow-hidden">
        <div className="absolute top-0 right-0 p-4 opacity-10">
          <Bot className="w-32 h-32 text-indigo-600" />
        </div>
        
        <div className="relative z-10">
          <h3 className="text-lg font-semibold text-indigo-900 mb-4 flex items-center">
            <Sparkles className="w-5 h-5 mr-2 text-indigo-600" />
            AI Hygiene Analysis
          </h3>
          
          <div className="bg-white/80 backdrop-blur-sm p-4 rounded-lg border border-indigo-100 shadow-sm min-h-[200px]">
            {aiAnalysis ? (
              <p className="text-indigo-900 leading-relaxed whitespace-pre-line text-sm md:text-base">
                {aiAnalysis}
              </p>
            ) : (
               <div className="flex items-center justify-center h-full text-indigo-400">
                 <span className="animate-pulse">Generating insights...</span>
               </div>
            )}
          </div>
          
          <div className="mt-4 flex items-start space-x-2">
            <AlertTriangle className="w-4 h-4 text-indigo-400 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-indigo-400">
              Insight generated by Gemini 2.5 Flash. Based on processing metadata only; raw phone numbers are not sent to AI.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};